### ISSUE TITLE
Collection Edit page tip refers to non-existent "save button"

### ISSUE THREAD

**Issue by atz** [samvera-labs/hyrax#1020]
- Share with another user

Alert/tip says `Permissions are not saved until the "Save" button is pressed at the bottom of the page.`  But there is no "Save" button.  

![screen shot 2017-05-22 at 6 47 34 pm](https://cloud.githubusercontent.com/assets/109954/26335202/2cb03164-3f1f-11e7-86c8-b994b68d27cf.png)

Issues:
- Mismatch between `"Save"` button and `"Update Collection"`
- `"Edit Access"` vs. `"Edit"`
- Group permissions fail to save or fail to display (#1019)

**Comment by laritakr** [comment]
Regarding issue 2, what do we want the text to say?

https://github.com/projecthydra-labs/hyrax/blob/master/lib/hyrax/configuration.rb#L382-L392

**Comment by ggeisler** [comment]
@laritakr Assuming issue 2 is the terminology for "edit access" I'd suggest "Edit access". That would be consistent with the proposal for the similar Works Sharing section of ticket #695.  (In that ticket "access" is capitalized but I think it should be lower-case.)

If you're working on this ticket please see my recent comment in #1019, which perhaps would have been more applicable to this ticket. I summarized the proposed rearrangement of sharing elements there.

**Comment by laritakr** [comment]
@ggeisler Thanks for the feedback. 

I believe this ticket is only to change the wording inconsistencies, and #1019 covers the rearrangement you mentioned. At least that's all I intended to work on here since the third point links to a separate issue. (And because I'm going on vacation and don't have time for more than this!)

**Comment by ggeisler** [comment]
@laritakr Oh okay, sounds good.

**Comment by laritakr** [comment]
@ggeisler So just to be clear, I should change both "Edit Access" and "Edit"  to "Edit access" (lower case a?)  I believe this affects the dropdown options for choosing access, as well as the display of what accesses are selected.

**Comment by ggeisler** [comment]
@laritakr I think the dropdown option should just be "Edit" since the dropdown label includes the word "access."

But in the list of existing permissions, "Edit access" is better because we don't have a heading that uses the word "access."

Hopefully it's possible for those two instances to use different terminology?

**Comment by laritakr** [comment]
@ggeisler Anything is possible, lol.  But that makes it more work so it probably won't happen until after my vacation. I'm pretty limited in time today. 

So to be clear... 

- Where it says "Edit Access" on the view, it should say "Edit access."
- Where it says "Edit" on the view, it should also say "Edit access."
- Where it says "Edit" in the dropdown, it should not change.
- The other capitalization in the dropdown should not change.

If there are any changes to what I've written above, please note them. I'll do the work after I return from vacation.

**Comment by ggeisler** [comment]
@laritakr Sure, my suggestions are what I'd recommend we aim for in the long-term, but if it can't all be done in the short-term I have no objection. I think the changes will improve things either way.

> Where it says "Edit Access" on the view, it should say "Edit access."

In the "Currently Shared With" section listing the current permissions, correct.

> Where it says "Edit" on the view, it should also say "Edit access."

I guess I don't know where it says "Edit" in the view, except in the case of the next item. So not sure how to answer this item.

> Where it says "Edit" in the dropdown, it should not change.

Correct.

> The other capitalization in the dropdown should not change.

Correct.

**Comment by laritakr** [comment]
@ggeisler yes, the next item(s) as there can be multiple, are what I was referring to. I was vague because I assume it would affect both view and edit pages, but obviously we want consistency so that's good.

**Comment by ggeisler** [comment]
@laritakr Okay, sounds good.
