### ISSUE TITLE
Unable to use MySQL database

### ISSUE THREAD

**Issue by revgum** [samvera-labs/hyrax#1043]
The line at https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/workflow/permission_query.rb#L261 seems to be one that causes the query to fail when using MySQL as the Hyrax database. 

```
 ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the
manual that corresponds to your MySQL server version for the right syntax to use near 'integer)
 FROM `sipity_agents` WHERE (`sipity_agents`.`id` IN (SELECT `sipity_wor' at line 1: SELECT
 `users`.* FROM `users` WHERE `users`.`id` IN (SELECT CAST(`sipity_agents`.`proxy_for_id` AS
 integer) FROM `sipity_agents` WHERE (`sipity_agents`.`id` IN (SELECT
 `sipity_workflow_responsibilities`.`agent_id` FROM `sipity_workflow_responsibilities` WHERE
 `sipity_workflow_responsibilities`.`workflow_role_id` IN (SELECT `sipity_workflow_roles`.`id`
FROM `sipity_workflow_roles` WHERE `sipity_workflow_roles`.`role_id` IN (3))) OR
`sipity_agents`.`id` IN (SELECT `sipity_entity_specific_responsibilities`.`agent_id` FROM
`sipity_entity_specific_responsibilities` WHERE
`sipity_entity_specific_responsibilities`.`workflow_role_id` IN (SELECT `sipity_workflow_roles`.`id`
FROM `sipity_workflow_roles` WHERE `sipity_workflow_roles`.`role_id` IN (3)) AND
`sipity_entity_specific_responsibilities`.`entity_id` = '2')) AND `sipity_agents`.`proxy_for_type` =
'User')):
```

**Comment by jcoyne** [comment]
You might want to try:
```
SELECT CAST(`sipity_agents`.`proxy_for_id` AS SIGNED) ...
```

**Comment by jcoyne** [comment]
This is the line:

https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/workflow/permission_query.rb#L261

**Comment by revgum** [comment]
Casting to signed breaks Postgres. See below:
> PG::UndefinedObject: ERROR: type "signed" does not exist LINE 1: ...IN (SELECT CAST("sipity_agents"."proxy_for_id" AS signed) FR... ^ : SELECT "users".* FROM "users" WHERE "users"."id" IN (SELECT CAST("sipity_agents"."proxy_for_id" AS signed) FROM "sipity_agents" WHERE ("sipity_agents"."id" IN (SELECT "sipity_workflow_responsibilities"."agent_id" FROM "sipity_workflow_responsibilities" WHERE "sipity_workflow_responsibilities"."workflow_role_id" IN (SELECT "sipity_workflow_roles"."id" FROM "sipity_workflow_roles" WHERE "sipity_workflow_roles"."role_id" IN (2))) OR "sipity_agents"."id" IN (SELECT "sipity_entity_specific_responsibilities"."agent_id" FROM "sipity_entity_specific_responsibilities" WHERE "sipity_entity_specific_responsibilities"."workflow_role_id" IN (SELECT "sipity_workflow_roles"."id" FROM "sipity_workflow_roles" WHERE "sipity_workflow_roles"."role_id" IN (2)) AND "sipity_entity_specific_responsibilities"."entity_id" = '1')) AND "sipity_agents"."proxy_for_type" = 'User')

I've solved this, one way, with an update to the PR this is being addressed with.
