### ISSUE TITLE
Simplify path for spec/actors/hyrax/actors/

### ISSUE THREAD

**Issue by darrenleeweber** [samvera-labs/hyrax#1053]
### Descriptive summary

```
git mv spec/actors/hyrax/actors/* spec/actors/hyrax/
```

There are too many `actors` in this spec path; it's not consistent with most other spec paths.

**Comment by jcoyne** [comment]
the first part `spec/actors` is just the organizing directory. The second part `hyrax/actors/*` is because the modules are actually named `Hyrax::Actors::*`.  So this would be the right thing to do only if `Actors` was not part of the module namespace.
