### ISSUE TITLE
Admins can't see 'Share My Work' if registered users are removed from default admin set

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyrax#1094]
### Descriptive summary

Removing ‘registered users’ from the default admin set will remove the Share Your Work button for everyone, including admins.

[ observed in  Hyku v1.0.0.beta1 ]

**Comment by mjgiarlo** [comment]
I believe #1142 will address this.

**Comment by jcoyne** [comment]
The button is removed if the current user does not have permission to create works in any admin set.  It is not specific to the default admin set or the "registered users". I believe this is appropriate behavior.

**Comment by geekscruff** [comment]
Yes I think the registered bit is a red herring, the problem is down to the admin not being a 'manager' as noted by @mjgiarlo :point_up: ... I'll close
