### ISSUE TITLE
Location field is single rather than multi-value

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyrax#1125]
### Descriptive summary

It is only possible to add a single 'location' to a Work. It should be possible to add multiple locations.

### Rationale

In line with other fields, there is no rationale for making this a single property.

### Expected behavior

I can add more than one location.

### Actual behavior

I can only add one location.

### Steps to reproduce the behavior

1. Create a work
2. Add a location

### Related work

Related to #1066

**Comment by jcoyne** [comment]
@geekscruff I think this is already fixed by https://github.com/samvera-labs/hyrax/pull/1121.  Please reopen if I'm mistaken.
