### ISSUE TITLE
Assigning workflow roles in Administration UI results in "Unauthorized" error

### ISSUE THREAD

**Issue by bess** [samvera-labs/hyrax#1145]
### Descriptive summary

In Hyrax 1.x, as an admin user, even one who owns an AdminSet, if I attempt to grant workflow permissions to another user the operation fails and I get an error page saying "Unauthorized
The page you have tried to access is private"

### Rationale

We need application administrators to be able to share approval permissions for workflows with other users. 

### Expected behavior

I expect to be able to assign roles to other users via the admin UI. 

### Actual behavior

Attempting to assign workflow roles results in an error.

### Steps to reproduce the behavior

1. As an admin user who also has the "managing" role for an admin set, go to the Administration hyrax screen.
1. Select Workflows --> Roles from the menu on the left
1. Select any user from the user menu, and an active admin set role from the "Workflow role" menu
1. Click "save"
1. You get an error page that says "Unauthorized
The page you have tried to access is private" and your workflow operation has not occurred. 

### Related work
I am going to try to insert a `byebug` and see if I can figure out the exact failure.

**Comment by bess** [comment]
The problem is in the can can authorization: 
```
authorize! :create, Sipity::WorkflowResponsibility
```

If I bypass that line using byebug, the workflow update happens correctly.

**Comment by mjgiarlo** [comment]
After chatting with @bess on Slack today, I believe we concluded that this was caused by laevigata overriding one of Hyrax's ability methods and not calling `super`. If that's true, feel free to close. Thanks!

**Comment by bess** [comment]
Yup, that fixed it. Thanks for your help, @mjgiarlo!
