### ISSUE TITLE
An admin user should be able to advance the workflow state of any work in any workflow

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyrax#185]
<a href="https://github.com/straleyb"><img src="https://avatars.githubusercontent.com/u/6424683?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [straleyb](https://github.com/straleyb)**
_Monday Nov 07, 2016 at 16:52 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2860_

----

As an admin user, I should be able to update a work's state even if I haven't explicitly been granted a role in that workflow.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 05, 2016 at 17:51 GMT_

----

@vantuyls @hannahfrost I think we need to back this feature with more detail on when and why this is needed. cc: @jcoyne 

Bumping to phase 2 for now.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 05, 2016 at 17:55 GMT_

----

If we do decide to work on this, it may be related to the following (as yet unwritten) story: "Admins should be able to edit all repository objects regardless of stored ACLs" (related to https://github.com/projecthydra/sufia/issues/2946)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Dec 05, 2016 at 18:22 GMT_

----

This is related to the idea that the Admin has complete control over repository functionality. Per our discussion on Slack this morning, i'm not sure that's necessarily a fair assumption and this may be more of a repository by repository role management issue. If role management allows one to set up an admin to be able to touch everything in the repository, then we're good. Are role-related issues labelled in any way?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 05, 2016 at 18:33 GMT_

----

@vantuyls :speech_balloon: 
> Are role-related issues labelled in any way?

No. Not yet anyway.

**Comment by mjgiarlo** [comment]
@vantuyls @hannahfrost How high of a priority is this?

**Comment by vantuyls** [comment]
i think if, for example, a reviewer is the only one who can advance something in a workflow we would have real problems. it is not uncommon for us to have urgency for deposit that requires a person who isn't the "normal" one doing the review to do that work. This is why i like the idea of an admin for an admin set being able to take action at all workflow steps. 

That said, if my use case is too special snowflake, if there is another way to specify this behavior for the admin set or the workflow, i'm okay with that, too.

**Comment by hannahfrost** [comment]
>  i like the idea of an admin for an admin set being able to take action at all workflow steps.

I'm with @vantuyls. That is entirely consistent with the permissions breakdown I spec'ed for Hyku. And I feel implementing this is high priority, but I also don't know what other work this requirement is up against, the level of effort, and other constraints.

**Comment by mjgiarlo** [comment]
@vantuyls @hannahfrost @jcoyne This is already done for the following users:

* The admin user that created the Admin Set
* Any user listed as a Manager for the Admin Set

This is *not* done for any other users that may be administrators. Does this need to be available to all administrative users, or is it acceptable for now to expect this to be controlled via the Admin Set Managers implementation we already have?

**Comment by hannahfrost** [comment]
@mjgiarlo I think completing this work is a priority, so that an Admin could participate in the workflow by default, and not need to take on a different role.

**Comment by mjgiarlo** [comment]
@hannahfrost OK. @jcoyne might a lightweight way to handle this be:

* Add the 'admin' group to the managers of every admin set when it's created
* Prevent the 'admin' group from being removed from this list (or hide it from being shown)

?

**Comment by mjgiarlo** [comment]
Design comments on the above, @ggeisler, particularly the second bullet point?

**Comment by ggeisler** [comment]
@mjgiarlo The above makes sense to me. I'd lean towards showing the Admin group, just so the Admins' privileges are explicit, but agree the Admin group should not be removeable.

If it seems like a mockup would help, feel free to add a design needed label.

**Comment by mjgiarlo** [comment]
Note that this ticket may require an upgrade tool (rake task) to automatically add the admin group to all previously created admin sets.

**Comment by mjgiarlo** [comment]
Discussed on May 17th with @jcoyne and @carrickr. We were wondering whether granting repo admins "god status" with workflows (allowing them to touch every entity in every state in every workflow) would make it difficult or impossible for them to make sense of, e.g., the Review Submissions view, if a user is both a repo admin and an Admin Set manager for one Admin Set. How do I find my Admin Set materials when I see everything in the repository? For that reason, we were thinking this might be a good issue to bounce back into Design Needed. One idea was we could add a widget to the Review Submissions view (and perhaps others?) that allows a repo admin to say "show me everything, not just stuff I have an explicit role in."

Thoughts, @hannahfrost @vantuyls @ggeisler?

**Comment by ggeisler** [comment]
@mjgiarlo I'd be happy to revisit this with your comments above, which make sense to me on first glance, as input. Please work with @hannahfrost to prioritize it with other design needed tickets so I get to it in the right order.

**Comment by mjgiarlo** [comment]
Thanks, @ggeisler! @hannahfrost do you mind taking a gander at the Design Needed column in Waffle and shuffling things into priority order? LMK if I can help.

**Comment by vantuyls** [comment]
@mjgiarlo i like the suggestion of "show me everything". would be intersted to see the design mockups.

**Comment by ggeisler** [comment]
This is not much of a mockup, but it seems like maybe all we need is to add a checkbox that gives the admin the ability to say she wants to see everything under review, not just what is shown in the table by default.

So, by default the table just shows works under review for admin sets the user is manager or otherwise a reviewer for (current behavior, I think?).

If the user is a repository administrator only, show the checkbox added in the mockup below. Checking the box updates the table with all works in the repo under review. Unchecking the boxes updates to remove those not part of the user's admin sets.

![index_workflow____institution_digital_repository](https://cloud.githubusercontent.com/assets/101482/26516402/a3b817ea-423a-11e7-8ea0-baf966676636.png)

**Comment by vantuyls** [comment]
works for me!

**Comment by hannahfrost** [comment]
@ggeisler @mjgiarlo I think we are ready to move this into the Ready column. Agreed?

**Comment by mjgiarlo** [comment]
@hannahfrost Given how much discussion there's been, I suspect we should close this issue and write up two new ones: one for adding the 'admin' group to every AS's managers list, and another for the "Show all works under review" checkbox that @ggeisler designer. I'll do that and mark both as ready.

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler @jcoyne @vantuyls Decomposed into #1142 and #1143. Thanks for helping to make this work actionable!

Closing.
